version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - mvn package
      - mv target/my-web-app.war my-web-app.war
artifacts:
  files:
    - .ebextensions/**/*
    - my-web-app.war
  base-directory: 'target/my-web-app'
